### ISSUE TITLE
Error when running local integration tests using the latest nodeshift and openshift-rest-client

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/rhoaster#29]
A new version of rhoaster was published and it is using the latest version of nodeshift and openshift-rest-client.

The previous rhoaster version `0.2.0` was pointing to the deprecated bucharest-gold image:

```console
15:31 $ npm run test:integration

> nodejs-rest-http@3.0.0 test:integration /home/hf/Documents/nodejs-rest-http
> tape test/integration/*.js | tap-spec

    No deployment found. Deploying...
    2019-10-24T18:31:51.700Z INFO loading configuration
    2019-10-24T18:31:51.701Z INFO using namespace myproject at https://192.168.99.101:8443
    2019-10-24T18:31:51.704Z INFO creating archive of package.json, app.js, public, bin, LICENSE, licenses
    2019-10-24T18:31:51.719Z INFO using existing build configuration nodejs-rest-http-s2i
    2019-10-24T18:31:51.724Z INFO using existing image stream nodejs-rest-http
    2019-10-24T18:31:51.724Z INFO uploading binary archive /home/hf/Documents/nodejs-rest-http/tmp/nodeshift/build/archive.tar
    2019-10-24T18:31:54.446Z INFO binary upload complete
    2019-10-24T18:31:54.446Z INFO waiting for build to finish
    2019-10-24T18:31:57.516Z TRACE Using bucharestgold/centos7-s2i-nodejs:latest as the s2i builder image
    2019-10-24T18:31:57.516Z TRACE ---> Installing application source
    2019-10-24T18:31:57.516Z TRACE ---> Building your Node application from source
    2019-10-24T18:31:57.516Z TRACE Current git config
```

So a new version was published to fix that, but an issue was found:

```console
$ npm run test:integration

> nodejs-rest-http@3.0.0 test:integration /home/hf/Documents/nodejs-rest-http
> tape test/integration/*.js | tap-spec

kubernetes-client deprecated require('kubernetes-client').config, use require('kubernetes-client/backends/request').config. node_modules/openshift-rest-client/lib/openshift-rest-client.js:25:17
kubernetes-client deprecated require('kubernetes-client').config, use require('kubernetes-client/backends/request').config. node_modules/openshift-rest-client/index.js:23:39
TypeError: openshift is not a function
    at Object.deploy (/home/hf/Documents/nodejs-rest-http/node_modules/rhoaster/index.js:40:12)


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-rest-http@3.0.0 test:integration: `tape test/integration/*.js | tap-spec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nodejs-rest-http@3.0.0 test:integration script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hf/.npm/_logs/2019-10-24T18_45_17_405Z-debug.log
```

**Comment by lholmquist** [comment]
> TypeError: openshift is not a function
    at Object.deploy (/home/hf/Documents/nodejs-rest-http/node_modules/rhoaster/index.js:40:12)


Yup,  the 2.x version of the openshift-rest-client changed how it gets instantiated,  so it makes sense that it would break

**Comment by helio-frota** [comment]
fixed thanks!
```
2019-10-25T18:19:40.227Z INFO Using s2i image nodeshift/centos7-s2i-nodejs with tag latest
```
